version: '3'
services:
  php:
    # image: php:7.3-apache
    build: .
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: mysql:5.7.40
    environment: 
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_pro1
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 12345
    ports:
      - 3306:3306